### ISSUE TITLE
static-ness is bad

### ISSUE THREAD

**Issue by gemmell** [luzzif/websocket-heartbeats#1]
I believe that due to everything in HeartbeatHandler being static, that it's actually getting confused within the related binance-api package. Essentially for each ws stream that you have open, they're all operating on a single static heartbeat despite several different ws streams being open.

Secondly, I would like to direct you to the implementation of the heartbeat at https://github.com/websockets/ws under `How to detect and close broken connections?` - there's some minor differences between your implementation and theirs which may have an effect.

**Comment by luzzif** [comment]
You are right for what concerns staticness, which I removed from the latest release (1.1.1). As for the tip about terminating a broken connection, I now call ```terminate``` on the websocket object. Thanks!

**Comment by gemmell** [comment]
Just as a note to the differences, they also use `wss.on('connection'` instead of `open` - not sure if it's of any concequence

**Comment by luzzif** [comment]
For that part, I took a look at [their official API documentation](https://github.com/websockets/ws/blob/master/doc/ws.md#class-websocket) and I saw there was only the ```open``` event, so I just used it instead of the ```connection``` one.
